"""add user role and qa_logs table

Revision ID: a632c3abf6a8
Revises: 
Create Date: 2026-09-15 17:02:51.420974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a632c3abf6a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提问用户ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='用户原始问题'),
    sa.Column('answer_summary', sa.String(length=500), nullable=True, comment='回答摘要（前500字）'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('hit_knowledge', sa.Boolean(), nullable=True, comment='是否命中知识库'),
    sa.Column('status', sa.String(length=20), server_default='success', nullable=False, comment='状态：success/failed'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_logs_create_time'), 'qa_logs', ['create_time'], unique=False)
    op.create_index(op.f('ix_qa_logs_id'), 'qa_logs', ['id'], unique=False)
    op.create_index(op.f('ix_qa_logs_user_id'), 'qa_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False, comment='角色：user/admin'))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '系统用户表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='账号创建时间',
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名（唯一）',
               existing_comment='用户名',
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_qa_logs_user_id'), table_name='qa_logs')
    op.drop_index(op.f('ix_qa_logs_id'), table_name='qa_logs')
    op.drop_index(op.f('ix_qa_logs_create_time'), table_name='qa_logs')
    op.drop_table('qa_logs')
    # ### end Alembic commands ###
